//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dsw2026Tpi.CrossCutting.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorCodes() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Dsw2026Tpi.CrossCutting.Resources.ErrorCodes", typeof(ErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno ya se encuentra reservado.
        /// </summary>
        public static string APPOINTMENT_CONFLICT {
            get {
                return ResourceManager.GetString("APPOINTMENT_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se puede reservar un turno en fechas/horas pasadas.
        /// </summary>
        public static string APPOINTMENT_IN_PAST {
            get {
                return ResourceManager.GetString("APPOINTMENT_IN_PAST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI debe tener entre 7 y 10 dígitos..
        /// </summary>
        public static string APPOINTMENT_INVALID_DNI {
            get {
                return ResourceManager.GetString("APPOINTMENT_INVALID_DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Solo se puede cancelar una cita que se encuentre en estado &apos;Reservada&apos;.
        /// </summary>
        public static string APPOINTMENT_NOT_CANCELLABLE {
            get {
                return ResourceManager.GetString("APPOINTMENT_NOT_CANCELLABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos.
        /// </summary>
        public static string AUTHENTICATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHENTICATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se requieren permisos para la operación solicitada.
        /// </summary>
        public static string AUTHORIZATION_FAILED {
            get {
                return ResourceManager.GetString("AUTHORIZATION_FAILED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Debe indicar al menos un día de atención.
        /// </summary>
        public static string AVAILABILITY_EMPTY_DAYS {
            get {
                return ResourceManager.GetString("AVAILABILITY_EMPTY_DAYS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  El día indicado no es válido.
        /// </summary>
        public static string AVAILABILITY_INVALID_DAY {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_DAY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El horario de inicio debe ser menor al horario de fin.
        /// </summary>
        public static string AVAILABILITY_INVALID_TIME_RANGE {
            get {
                return ResourceManager.GetString("AVAILABILITY_INVALID_TIME_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El horario se superpone con otra disponibilidad del médico.
        /// </summary>
        public static string AVAILABILITY_OVERLAP {
            get {
                return ResourceManager.GetString("AVAILABILITY_OVERLAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La matrícula del médico es obligatoria.
        /// </summary>
        public static string DOCTOR_INVALID_LICENSE {
            get {
                return ResourceManager.GetString("DOCTOR_INVALID_LICENSE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del médico debe tener al menos 3 caracteres.
        /// </summary>
        public static string DOCTOR_INVALID_NAME {
            get {
                return ResourceManager.GetString("DOCTOR_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La entidad {0} no se encontró.
        /// </summary>
        public static string ENTITY_NOTFOUND {
            get {
                return ResourceManager.GetString("ENTITY_NOTFOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno (availabilityId) es obligatorio.
        /// </summary>
        public static string INVALID_AVAILABILITY_ID {
            get {
                return ResourceManager.GetString("INVALID_AVAILABILITY_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a  El motivo es obligatorio y debe tener por lo menos 5 caracteres.
        /// </summary>
        public static string INVALID_REASON {
            get {
                return ResourceManager.GetString("INVALID_REASON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe un paciente registrado con ese DNI.
        /// </summary>
        public static string PATIENT_DNI_TAKEN {
            get {
                return ResourceManager.GetString("PATIENT_DNI_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El DNI debe tener 7 u 8 dígitos.
        /// </summary>
        public static string PATIENT_INVALID_DNI {
            get {
                return ResourceManager.GetString("PATIENT_INVALID_DNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El email ingresado no es válido.
        /// </summary>
        public static string PATIENT_INVALID_EMAIL {
            get {
                return ResourceManager.GetString("PATIENT_INVALID_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El límite de solicitudes permitidas fue excedido. Espere e intente nuevamente..
        /// </summary>
        public static string RATE_LIMIT_EXCEDED {
            get {
                return ResourceManager.GetString("RATE_LIMIT_EXCEDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error al registrar el usuario.
        /// </summary>
        public static string REGISTER_USER_CONFLICT {
            get {
                return ResourceManager.GetString("REGISTER_USER_CONFLICT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos de registración de usuario no válidos.
        /// </summary>
        public static string REGISTER_USER_INVALID {
            get {
                return ResourceManager.GetString("REGISTER_USER_INVALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El turno seleccionado no corresponde al médico que se indicó.
        /// </summary>
        public static string SLOT_DOCTOR_MISMATCH {
            get {
                return ResourceManager.GetString("SLOT_DOCTOR_MISMATCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La descripción de la especialidad debe tener entre 10 y 100 caracteres.
        /// </summary>
        public static string SPECIALTY_INVALID_DESCRIPTION {
            get {
                return ResourceManager.GetString("SPECIALTY_INVALID_DESCRIPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de la especialidad debe tener entre 3 y 100 caracteres.
        /// </summary>
        public static string SPECIALTY_INVALID_NAME {
            get {
                return ResourceManager.GetString("SPECIALTY_INVALID_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ya existe una especialidad con ese nombre.
        /// </summary>
        public static string SPECIALTY_NAME_TAKEN {
            get {
                return ResourceManager.GetString("SPECIALTY_NAME_TAKEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se produjo un error no controlado.
        /// </summary>
        public static string UNHANDLED_ERROR {
            get {
                return ResourceManager.GetString("UNHANDLED_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Uno o más errores de validación ocurrieron.
        /// </summary>
        public static string VALIDATION_ERROR {
            get {
                return ResourceManager.GetString("VALIDATION_ERROR", resourceCulture);
            }
        }
    }
}
